### ISSUE TITLE
Where is startup?

### ISSUE THREAD

**Issue by redj101** [C0D3D3V/Moodle-Downloader#16]
I don't understand the part "Put watch -n 3600 python moodleCrawler.py in startup to fetch the files every hour"

Is it the Windows startup folder? If so, how do you put a command in there?

Thank you

**Comment by C0D3D3V** [comment]
To run the script you have to install python2 and all the dependencies listed in the readme (maybe you need to restart your computer). Then you can open a terminal and navigate to the folder containing the moodleCrawler.py: 'cd C://Path/To/Folder ' then you can run the script with 'python2 moodleCrawler.py'

**Comment by C0D3D3V** [comment]
Did this help you? Can I close the issue?
