### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by steelstrings** [C0D3D3V/Moodle-Downloader#21]
moodle instance (baseurl): https://moodle.bulme.at
authurl: https://moodle.bulme.at/login/index.php

```
python2 moodleCrawler.py 
09:11:01 Moodle Crawler started working.
09:11:01 Try to login...
09:11:01 Download has started.
09:11:01 No Content-Length available.
09:11:01 Downloaded 29405 bytes
09:11:01 Download complete.
09:11:01 Cannot connect to moodle or Moodle has changed. Crawler is not logged in. Check your login data.
```

I have to add that my password does contain special characters, but this shouldn't be a problem right?

**Comment by C0D3D3V** [comment]
Did you put double quotes around the password? 
As long as you have no double quote in your password it should be fine.

I checked your Moodle, it uses a logintoken. So try to set uselogintoken = true
If it still doesn't work, set loglevel = 5 and send me the new log.

**Comment by steelstrings** [comment]
Login works fine now, which is strange, because I tried `uselogintoken = true` before and I got the same error message (`Cannot connect to moodle or Moodle has changed. Crawler is not logged in. Check your login data.`).

Apart from that I'm not really able to download any courses, but I'm gonna file a separate bug report for that one.
